#include "CamFacade.h"

#include "CamJob.h"
#include "ProfileOperation.h"
#include "PocketOperation.h"
#include "DrillOperation.h"
#include "FacingOperation.h"
#include "GCodeGenerator.h"
#include "GenericPostProcessor.h"

#include <fstream>
#include <gp_Pnt.hxx>

namespace CADNC {

CamFacade::CamFacade()
    : job_(std::make_unique<MilCAD::CamJob>())
{
}

CamFacade::~CamFacade() = default;

void CamFacade::setStock(double length, double width, double height)
{
    MilCAD::Stock stock;
    stock.origin = gp_Pnt(0, 0, 0);
    stock.sizeX = length;
    stock.sizeY = width;
    stock.sizeZ = height;
    stock.material = "Aluminum 6061";
    job_->setStock(stock);
}

int CamFacade::addEndMill(const std::string& name, double diameter, double fluteLength)
{
    static int nextToolId = 1;
    MilCAD::Tool tool;
    tool.id = nextToolId++;
    tool.name = name;
    tool.type = MilCAD::ToolType::EndMill;
    tool.diameter = diameter;
    tool.fluteLength = fluteLength;
    tool.overallLength = fluteLength * 2.0;
    job_->toolLibrary().add(tool);
    return tool.id;
}

int CamFacade::addToolController(int toolId, double spindleRpm, double feedXY, double feedZ)
{
    MilCAD::ToolController tc;
    tc.id = nextToolControllerId_++;
    tc.toolId = toolId;
    tc.spindleRpm = spindleRpm;
    tc.feedCut = feedXY;
    tc.feedPlunge = feedZ;
    tc.feedRapid = 3000.0;
    job_->addToolController(tc);
    return tc.id;
}

int CamFacade::addProfileOp(int toolControllerId, double depth, double stepDown,
                            double x1, double y1, double x2, double y2)
{
    auto op = std::make_unique<MilCAD::ProfileOperation>();
    op->setToolControllerId(toolControllerId);
    op->setTargetZ(-depth);
    op->setStepDown(stepDown);

    // Build rectangular contour
    std::vector<gp_Pnt> contour = {
        gp_Pnt(x1, y1, 0), gp_Pnt(x2, y1, 0),
        gp_Pnt(x2, y2, 0), gp_Pnt(x1, y2, 0),
        gp_Pnt(x1, y1, 0)  // close
    };
    op->setContour(contour);

    int id = static_cast<int>(job_->operationCount()) + 1;
    job_->addOperation(std::move(op));
    return id;
}

int CamFacade::addPocketOp(int toolControllerId, double depth, double stepDown, double stepOver,
                           double x1, double y1, double x2, double y2)
{
    auto op = std::make_unique<MilCAD::PocketOperation>();
    op->setToolControllerId(toolControllerId);
    op->setTargetZ(-depth);
    op->setStepDown(stepDown);
    op->setStepOver(stepOver);
    op->setBounds(x1, y1, x2, y2);

    int id = static_cast<int>(job_->operationCount()) + 1;
    job_->addOperation(std::move(op));
    return id;
}

int CamFacade::addDrillOp(int toolControllerId, double depth,
                          const std::vector<std::pair<double,double>>& points)
{
    auto op = std::make_unique<MilCAD::DrillOperation>();
    op->setToolControllerId(toolControllerId);
    op->setTargetZ(-depth);

    std::vector<gp_Pnt> pts;
    pts.reserve(points.size());
    for (const auto& [x, y] : points)
        pts.emplace_back(x, y, 0);
    op->setPoints(pts);

    int id = static_cast<int>(job_->operationCount()) + 1;
    job_->addOperation(std::move(op));
    return id;
}

int CamFacade::addFacingOp(int toolControllerId, double depth, double stepOver)
{
    auto op = std::make_unique<MilCAD::FacingOperation>();
    op->setToolControllerId(toolControllerId);
    op->setTargetZ(-depth);
    op->setStepOver(stepOver);

    // Use stock for facing area
    op->setStock(job_->stock());

    int id = static_cast<int>(job_->operationCount()) + 1;
    job_->addOperation(std::move(op));
    return id;
}

std::vector<CamOpInfo> CamFacade::operations() const
{
    std::vector<CamOpInfo> result;
    for (const auto& op : job_->operations()) {
        CamOpInfo info;
        info.id = op->id();
        info.typeName = op->typeName();
        info.description = op->typeName() + " (ID:" + std::to_string(op->id()) + ")";
        result.push_back(std::move(info));
    }
    return result;
}

int CamFacade::operationCount() const
{
    return static_cast<int>(job_->operationCount());
}

std::string CamFacade::generateGCode() const
{
    MilCAD::GenericPostProcessor post(MilCAD::GenericPostFlavor::Fanuc);

    std::string fullCode;
    for (const auto& op : job_->operations()) {
        auto tp = op->generateToolpath();
        auto blocks = MilCAD::GCodeGenerator::generate(tp, post);
        fullCode += MilCAD::GCodeGenerator::toText(blocks);
        fullCode += "\n";
    }
    return fullCode;
}

std::string CamFacade::generateCodesysGCode() const
{
    // Use LinuxCNC flavor as closest to CODESYS generic format
    MilCAD::GenericPostProcessor post(MilCAD::GenericPostFlavor::LinuxCNC);

    std::string fullCode;
    fullCode += "; CODESYS SoftMotion CNC G-Code\n";
    fullCode += "; Generated by CADNC\n\n";

    for (const auto& op : job_->operations()) {
        auto tp = op->generateToolpath();
        auto blocks = MilCAD::GCodeGenerator::generate(tp, post);
        fullCode += MilCAD::GCodeGenerator::toText(blocks);
        fullCode += "\n";
    }
    return fullCode;
}

bool CamFacade::exportToFile(const std::string& filePath, bool codesys) const
{
    std::string gcode = codesys ? generateCodesysGCode() : generateGCode();
    if (gcode.empty()) return false;

    std::ofstream file(filePath);
    if (!file.is_open()) return false;

    file << gcode;
    return file.good();
}

} // namespace CADNC
