const char FreeCADInit[] ="# SPDX-License-Identifier: LGPL-2.1-or-later\n"
"\n"
"#***************************************************************************\n"
"#*   Copyright (c) 2001,2002 Jürgen Riegel <juergen.riegel@web.de>         *\n"
"#*   Copyright (c) 2025 Frank Martínez <mnesarco at gmail dot com>         *\n"
"#*                                                                         *\n"
"#*   This file is part of the FreeCAD CAx development system.              *\n"
"#*                                                                         *\n"
"#*   This program is free software  you can redistribute it and/or modify  *\n"
"#*   it under the terms of the GNU Lesser General Public License (LGPL)    *\n"
"#*   as published by the Free Software Foundation  either version 2 of     *\n"
"#*   the License, or (at your option) any later version.                   *\n"
"#*   for detail see the LICENCE text file.                                 *\n"
"#*                                                                         *\n"
"#*   FreeCAD is distributed in the hope that it will be useful,            *\n"
"#*   but WITHOUT ANY WARRANTY  without even the implied warranty of        *\n"
"#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *\n"
"#*   GNU Lesser General Public License for more details.                   *\n"
"#*                                                                         *\n"
"#*   You should have received a copy of the GNU Library General Public     *\n"
"#*   License along with FreeCAD  if not, write to the Free Software        *\n"
"#*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *\n"
"#*   USA                                                                   *\n"
"#*                                                                         *\n"
"#***************************************************************************/\n"
"\n"
"# FreeCAD init module - App\n"
"#\n"
"# Gathering all the information to start FreeCAD.\n"
"# This is the second of four init scripts:\n"
"# +------+------------------+-----------------------------+\n"
"# | This | Script           | Runs                        |\n"
"# +------+------------------+-----------------------------+\n"
"# |      | CMakeVariables   | always                      |\n"
"# | >>>> | FreeCADInit      | always                      |\n"
"# |      | FreeCADTest      | only if test and not Gui    |\n"
"# |      | FreeCADGuiInit   | only if Gui is up           |\n"
"# +------+------------------+-----------------------------+\n"
"\n"
"import FreeCAD\n"
"\n"
"App = FreeCAD\n"
"\n"
"App.Console.PrintLog(\"Init: starting App::FreeCADInit.py\\n\")\n"
"App.Console.PrintLog(\"░░░▀█▀░█▀█░▀█▀░▀█▀░░░█▀█░█▀█░█▀█░░\\n\")\n"
"App.Console.PrintLog(\"░░░░█░░█░█░░█░░░█░░░░█▀█░█▀▀░█▀▀░░\\n\")\n"
"App.Console.PrintLog(\"░░░▀▀▀░▀░▀░▀▀▀░░▀░░░░▀░▀░▀░░░▀░░░░\\n\")\n"
"\n"
"try:\n"
"    import sys\n"
"    import os\n"
"    import traceback\n"
"    import inspect\n"
"    from enum import IntEnum  # Leak to globals (backwards compat)\n"
"    from datetime import datetime  # Leak to globals (backwards compat)\n"
"    from pathlib import Path  # Removed manually\n"
"    import dataclasses\n"
"    import collections\n"
"    import collections.abc as coll_abc\n"
"    import platform\n"
"    import types\n"
"    import importlib.resources as resources\n"
"    import importlib\n"
"    import functools\n"
"    import re\n"
"    import pkgutil\n"
"except ImportError:\n"
"    App.Console.PrintError(\"\\n\\nSeems the python standard libs are not installed, bailing out!\\n\\n\")\n"
"    raise\n"
"\n"
"# ┌────────────────────────────────────────────────┐\n"
"# │ Logging Frameworks                             │\n"
"# └────────────────────────────────────────────────┘\n"
"\n"
"def __logger(fn):\n"
"    __logger.sep = \"\\n\"\n"
"    def wrapper(text: object, *, sep: str | None = None) -> None:\n"
"        fn(f\"{text!s}{__logger.sep if sep is None else sep}\")\n"
"    return wrapper\n"
"\n"
"Log = __logger(App.Console.PrintLog)\n"
"Msg = __logger(App.Console.PrintMessage)\n"
"Err = __logger(App.Console.PrintError)\n"
"Wrn = __logger(App.Console.PrintWarning)\n"
"Crt = __logger(App.Console.PrintCritical)\n"
"Ntf = __logger(App.Console.PrintNotification)\n"
"Tnf = __logger(App.Console.PrintTranslatedNotification)\n"
"\n"
"\n"
"class FCADLogger:\n"
"    \"\"\"\n"
"    Convenient class for tagged logging.\n"
"\n"
"    Example usage:\n"
"        >>> logger = FreeCAD.Logger(\'MyModule\')\n"
"        >>> logger.info(\'log test {}\',1)\n"
"        24.36053 <MyModule> <input>(1): test log 1\n"
"\n"
"    The default output format is:\n"
"        <timestamp> <tag> <source file>(line number): message\n"
"\n"
"    The message is formatted using new style Python string formatting, e.g.\n"
"    \'test {}\'.format(1). It is strongly recommended to not directly use\n"
"    Python string formatting, but pass additional argument indirectly through\n"
"    various logger print function, because the logger can skip string\n"
"    evaluation in case the logging level is disabled. For more options,\n"
"    please consult the docstring of __init__(), catch() and report().\n"
"\n"
"    To set/get logger level:\n"
"        >>> FreeCAD.setLogLevel(\'MyModule\',\'Trace\')\n"
"        >>> FreeCAD.getLogLevel(\'MyModule\')\n"
"        4\n"
"\n"
"    There are five predefined logger level, each corresponding to an integer\n"
"    value, as shown below together with the corresponding logger print\n"
"    method,\n"
"        0: Error, Logger.error()\n"
"        1: Warning, Logger.warn()\n"
"        2: Message, Logger.msg() or info()\n"
"        3: Log, Logger.log() or debug()\n"
"        4: Trace, Logger.trace()\n"
"\n"
"    FreeCAD.setLogLevel() supports both text and integer value, which allows\n"
"    you to define your own levels. The level set is persisted to user\n"
"    configuration file.\n"
"\n"
"    By default any tag has a log level of 2 for release, and 3 for debug\n"
"    build.\n"
"    \"\"\"\n"
"\n"
"    _levels = {\n"
"        \'Error\': 0,\n"
"        \'error\': 0,\n"
"        \'Warning\': 1,\n"
"        \'warn\': 1,\n"
"        \'Message\': 2,\n"
"        \'msg\': 2,\n"
"        \'info\': 2,\n"
"        \'Log\': 3,\n"
"        \'log\': 3,\n"
"        \'debug\': 3,\n"
"        \'Trace\': 4,\n"
"        \'trace\': 4,\n"
"    }\n"
"\n"
"    _printer = (\n"
"        App.Console.PrintError,\n"
"        App.Console.PrintWarning,\n"
"        App.Console.PrintMessage,\n"
"        App.Console.PrintLog,\n"
"        App.Console.PrintLog\n"
"    )\n"
"\n"
"    _defaults = (\n"
"        (\'printTag\', True),\n"
"        (\'noUpdateUI\', True),\n"
"        (\'timing\', True),\n"
"        (\'lineno\', True),\n"
"        (\'parent\', None),\n"
"        (\'title\', \'FreeCAD\'),\n"
"    )\n"
"\n"
"    printTag: bool\n"
"    noUpdateUI: bool\n"
"    timing: bool\n"
"    lineno: bool\n"
"    parent: \"FCADLogger\"\n"
"    title: str\n"
"\n"
"    def __init__(self, tag: str, **kwargs) -> None:\n"
"        \"\"\"\n"
"        Construct a logger instance.\n"
"\n"
"        Supported arguments are their default values are,\n"
"\n"
"        * tag: a string tag for this logger. The log level of this logger can be\n"
"               accessed using FreeCAD.getLogLevel(tag)/setLogLevel(tag,level).\n"
"               All logger instance with the same tag shares the same level\n"
"               setting.\n"
"\n"
"        * printTag (True): whether to print tag\n"
"\n"
"        * noUpdateUI (True): whether to update GUI when printing. This is useful\n"
"                             to show log output on lengthy operations. Be\n"
"                             careful though, this may allow unexpected user\n"
"                             interaction when the application is busy, which may\n"
"                             lead to crash\n"
"\n"
"        * timing (True): whether to print time stamp\n"
"\n"
"        * lineno (True): whether to print source file and line number\n"
"\n"
"        * parent (None): provide a parent logger, so that the log printing will\n"
"                         check for parent\'s log level in addition of its own\n"
"\n"
"        * title (\'FreeCAD\'): message box title used by report()\n"
"        \"\"\"\n"
"        self.tag = tag\n"
"        self.laststamp = datetime.now()\n"
"        for key, default in self._defaults:\n"
"            setattr(self, key, kwargs.get(key, default))\n"
"\n"
"    def _isEnabledFor(self, level: int) -> bool:\n"
"        \"\"\"\n"
"        Internal function to check for an integer log level.\n"
"\n"
"        * level: integer log level\n"
"        \"\"\"\n"
"        if self.parent and not self.parent._isEnabledFor(level):\n"
"            return False\n"
"        return App.getLogLevel(self.tag) >= level\n"
"\n"
"    def isEnabledFor(self, level: int | str) -> bool:\n"
"        \"\"\"\n"
"        To check for an integer or text log level.\n"
"\n"
"        * level: integer or text log level\n"
"        \"\"\"\n"
"        if not isinstance(level, int):\n"
"            level = self.__class__._levels[level]\n"
"        return self._isEnabledFor(level)\n"
"\n"
"    def _logger_method(name: str, level: int, level_name: str):  # pylint: disable=no-self-argument\n"
"        \"\"\"\n"
"        Create level logger.\n"
"        \"\"\"\n"
"        docstring = f\"\"\"\n"
"            \"{level_name}\" level log printer\n"
"\n"
"            * msg: message string. May contain new style Python string formatter.\n"
"\n"
"            This function accepts additional positional and keyword arguments,\n"
"            which are forward to string.format() to generate the logging\n"
"            message. It is strongly recommended to not directly use Python\n"
"            string formatting, but pass additional arguments here, because the\n"
"            printer can skip string evaluation in case the logging level is\n"
"            disabled.\n"
"            \"\"\"\n"
"\n"
"        def log_fn(self, msg: str, *args, **kwargs) -> None:\n"
"            if self._isEnabledFor(level):\n"
"                frame = kwargs.pop(\'frame\', 0) + 1\n"
"                self._log(level, msg, frame, args, kwargs)\n"
"\n"
"        log_fn.__doc__ = docstring\n"
"        log_fn.__name__ = name\n"
"        return log_fn\n"
"\n"
"    def _log(\n"
"            self,\n"
"            level: int,\n"
"            msg: str,\n"
"            frame: int = 0,\n"
"            args: tuple = (),\n"
"            kwargs: dict | None = None,\n"
"        ) -> None:\n"
"        \"\"\"\n"
"        Internal log printing function.\n"
"\n"
"        * level: integer log level\n"
"\n"
"        * msg: message, may contain new style string format specifier\n"
"\n"
"        * frame (0): the calling frame for printing source file and line\n"
"                        number.  For example, in case you have your own logging\n"
"                        function, and you want to show the callers source\n"
"                        location, then set frame to one.\n"
"\n"
"        * args: tuple for positional arguments to be passed to\n"
"                string.format()\n"
"\n"
"        * kwargs: dictionary for keyword arguments to be passed to\n"
"                    string.format()\n"
"        \"\"\"\n"
"\n"
"        if (args or kwargs) and isinstance(msg, str):\n"
"            if not kwargs:\n"
"                msg = msg.format(*args)\n"
"            else:\n"
"                msg = msg.format(*args, **kwargs)\n"
"\n"
"        prefix = \'\'\n"
"\n"
"        if self.timing:\n"
"            now = datetime.now()\n"
"            prefix += \'{} \'.format((now-self.laststamp).total_seconds())\n"
"            self.laststamp = now\n"
"\n"
"        if self.printTag:\n"
"            prefix += \'<{}> \'.format(self.tag)\n"
"\n"
"        if self.lineno:\n"
"            try:\n"
"                frame = sys._getframe(frame+1)\n"
"                prefix += \'{}({}): \'.format(os.path.basename(\n"
"                    frame.f_code.co_filename),frame.f_lineno)\n"
"            except Exception:\n"
"                frame = inspect.stack()[frame+1]\n"
"                prefix += \'{}({}): \'.format(os.path.basename(frame[1]),frame[2])\n"
"\n"
"        self.__class__._printer[level](\'{}{}\\n\'.format(prefix,msg))\n"
"\n"
"        if not self.noUpdateUI and App.GuiUp:\n"
"            import FreeCADGui\n"
"            try:\n"
"                FreeCADGui.updateGui()\n"
"            except Exception:\n"
"                pass\n"
"\n"
"    def _catch_logger_method(name: str, level: int, level_name: str):  # pylint: disable=no-self-argument\n"
"        \"\"\"\n"
"        Create level catch logger.\n"
"        \"\"\"\n"
"        docstring = f\"\"\"\n"
"            Catch any exception from a function and print as \"{level_name}\".\n"
"\n"
"            * msg: message string. Unlike log printer, this argument must not\n"
"                    contain any string formatter.\n"
"\n"
"            * func: a callable object\n"
"\n"
"            * args: tuple of positional arguments to be passed to func.\n"
"\n"
"            * kwargs: dictionary of keyword arguments to be passed to func.\n"
"            \"\"\"\n"
"\n"
"        def catch_fn(self, msg: str, func: callable, *args, **kwargs) -> object | None:\n"
"            return self._catch(level, msg, func, args, kwargs)\n"
"\n"
"        catch_fn.__doc__ = docstring\n"
"        catch_fn.__name__ = name\n"
"        return catch_fn\n"
"\n"
"    def _catch(\n"
"            self,\n"
"            level: int,\n"
"            msg: str,\n"
"            func: callable,\n"
"            args: tuple = (),\n"
"            kwargs: dict | None = None,\n"
"        ) -> object | None:\n"
"        \"\"\"\n"
"        Internal function to log exception of any callable.\n"
"\n"
"        * level: integer log level\n"
"\n"
"        * msg: message string. Unlike _log(), this argument must not contain\n"
"                any string formatter.\n"
"\n"
"        * func: a callable object\n"
"\n"
"        * args: tuple of positional arguments to be passed to func.\n"
"\n"
"        * kwargs: dictionary of keyword arguments to be passed to func.\n"
"        \"\"\"\n"
"        try:\n"
"            if not kwargs:\n"
"                kwargs = {}\n"
"            return func(*args, **kwargs)\n"
"        except Exception:\n"
"            if self._isEnabledFor(level):\n"
"                self._log(level, f\"{msg}\\n{traceback.format_exc()}\", frame=2)\n"
"        return None\n"
"\n"
"    def report(self, msg: str, func: callable, *args, **kwargs) -> object | None:\n"
"        \"\"\"\n"
"        Catch any exception report it with a message box.\n"
"\n"
"        * msg: message string. Unlike log printer, this argument must not\n"
"                contain any string formatter.\n"
"\n"
"        * func: a callable object\n"
"\n"
"        * args: tuple of positional arguments to be passed to func.\n"
"\n"
"        * kwargs: dictionary of keyword arguments to be passed to func.\n"
"        \"\"\"\n"
"        try:\n"
"            return func(*args, **kwargs)\n"
"        except Exception as e:\n"
"            self.error(f\"{msg}\\n{traceback.format_exc()}\", frame=1)\n"
"            if App.GuiUp:\n"
"                import FreeCADGui, PySide\n"
"                PySide.QtGui.QMessageBox.critical(\n"
"                    FreeCADGui.getMainWindow(),\n"
"                    self.title,\n"
"                    str(e),\n"
"                )\n"
"        return None\n"
"\n"
"    error = _logger_method(\"error\", 0, \"Error\")\n"
"    warn = _logger_method(\"warn\", 1, \"Warning\")\n"
"    msg = _logger_method(\"msg\", 2, \"Message\")\n"
"    log = _logger_method(\"log\", 3, \"Log\")\n"
"    trace = _logger_method(\"trace\", 4, \"Trace\")\n"
"    info = msg\n"
"    debug = log\n"
"\n"
"    catch = _catch_logger_method(\"catch\", 0, \"Error\")\n"
"    catchWarn = _catch_logger_method(\"catchWarn\", 1, \"Warning\")\n"
"    catchMsg = _catch_logger_method(\"catchMsg\", 2, \"Message\")\n"
"    catchLog = _catch_logger_method(\"catchLog\", 3, \"Log\")\n"
"    catchTrace = _catch_logger_method(\"catchTrace\", 4, \"Trace\")\n"
"    catchInfo = catchMsg\n"
"    catchDebug = catchLog\n"
"\n"
"\n"
"App.Logger = FCADLogger\n"
"\n"
"\n"
"# ┌────────────────────────────────────────────────┐\n"
"# │ App definitions                                │\n"
"# └────────────────────────────────────────────────┘\n"
"\n"
"# store the cmake variables\n"
"# This data comes from generated file src/App/CMakeScript.h and it is\n"
"# injected into globals in a previous stage.\n"
"App.__cmake__ = globals().get(\"cmake\", [])\n"
"\n"
"# store unit test names\n"
"App.__unit_test__ = []\n"
"\n"
"App.addImportType(\"FreeCAD document (*.FCStd)\", \"FreeCAD\")\n"
"\n"
"# set to no gui, is overwritten by InitGui\n"
"App.GuiUp = 0\n"
"\n"
"# fmt: off\n"
"# fill up unit definitions\n"
"\n"
"App.Units.NanoMetre     = App.Units.Quantity(\'nm\')\n"
"App.Units.MicroMetre    = App.Units.Quantity(\'um\')\n"
"App.Units.MilliMetre    = App.Units.Quantity(\'mm\')\n"
"App.Units.CentiMetre    = App.Units.Quantity(\'cm\')\n"
"App.Units.DeciMetre     = App.Units.Quantity(\'dm\')\n"
"App.Units.Metre         = App.Units.Quantity(\'m\')\n"
"App.Units.KiloMetre     = App.Units.Quantity(\'km\')\n"
"\n"
"App.Units.MilliLiter    = App.Units.Quantity(\'ml\')\n"
"App.Units.Liter         = App.Units.Quantity(\'l\')\n"
"\n"
"App.Units.Hertz         = App.Units.Quantity(\'Hz\')\n"
"App.Units.KiloHertz     = App.Units.Quantity(\'kHz\')\n"
"App.Units.MegaHertz     = App.Units.Quantity(\'MHz\')\n"
"App.Units.GigaHertz     = App.Units.Quantity(\'GHz\')\n"
"App.Units.TeraHertz     = App.Units.Quantity(\'THz\')\n"
"\n"
"App.Units.MicroGram     = App.Units.Quantity(\'ug\')\n"
"App.Units.MilliGram     = App.Units.Quantity(\'mg\')\n"
"App.Units.Gram          = App.Units.Quantity(\'g\')\n"
"App.Units.KiloGram      = App.Units.Quantity(\'kg\')\n"
"App.Units.Ton           = App.Units.Quantity(\'t\')\n"
"\n"
"App.Units.Second        = App.Units.Quantity(\'s\')\n"
"App.Units.Minute        = App.Units.Quantity(\'min\')\n"
"App.Units.Hour          = App.Units.Quantity(\'h\')\n"
"\n"
"App.Units.Ampere        = App.Units.Quantity(\'A\')\n"
"App.Units.NanoAmpere    = App.Units.Quantity(\'nA\')\n"
"App.Units.MicroAmpere   = App.Units.Quantity(\'uA\')\n"
"App.Units.MilliAmpere   = App.Units.Quantity(\'mA\')\n"
"App.Units.KiloAmpere    = App.Units.Quantity(\'kA\')\n"
"App.Units.MegaAmpere    = App.Units.Quantity(\'MA\')\n"
"\n"
"App.Units.Kelvin        = App.Units.Quantity(\'K\')\n"
"App.Units.MilliKelvin   = App.Units.Quantity(\'mK\')\n"
"App.Units.MicroKelvin   = App.Units.Quantity(\'uK\')\n"
"\n"
"App.Units.Mole          = App.Units.Quantity(\'mol\')\n"
"App.Units.NanoMole      = App.Units.Quantity(\'nmol\')\n"
"App.Units.MicroMole     = App.Units.Quantity(\'umol\')\n"
"App.Units.MilliMole     = App.Units.Quantity(\'mmol\')\n"
"\n"
"App.Units.Candela       = App.Units.Quantity(\'cd\')\n"
"\n"
"App.Units.Inch          = App.Units.Quantity(\'in\')\n"
"App.Units.Foot          = App.Units.Quantity(\'ft\')\n"
"App.Units.Thou          = App.Units.Quantity(\'thou\')\n"
"App.Units.Yard          = App.Units.Quantity(\'yd\')\n"
"App.Units.Mile          = App.Units.Quantity(\'mi\')\n"
"\n"
"App.Units.SquareFoot    = App.Units.Quantity(\'sqft\')\n"
"App.Units.CubicFoot     = App.Units.Quantity(\'cft\')\n"
"\n"
"App.Units.Pound         = App.Units.Quantity(\'lb\')\n"
"App.Units.Ounce         = App.Units.Quantity(\'oz\')\n"
"App.Units.Stone         = App.Units.Quantity(\'st\')\n"
"App.Units.Hundredweights= App.Units.Quantity(\'cwt\')\n"
"\n"
"App.Units.Newton        = App.Units.Quantity(\'N\')\n"
"App.Units.MilliNewton   = App.Units.Quantity(\'mN\')\n"
"App.Units.KiloNewton    = App.Units.Quantity(\'kN\')\n"
"App.Units.MegaNewton    = App.Units.Quantity(\'MN\')\n"
"\n"
"App.Units.NewtonPerMeter        = App.Units.Quantity(\'N/m\')\n"
"App.Units.MilliNewtonPerMeter   = App.Units.Quantity(\'mN/m\')\n"
"App.Units.KiloNewtonPerMeter    = App.Units.Quantity(\'kN/m\')\n"
"App.Units.MegaNewtonPerMeter    = App.Units.Quantity(\'MN/m\')\n"
"\n"
"App.Units.Pascal        = App.Units.Quantity(\'Pa\')\n"
"App.Units.KiloPascal    = App.Units.Quantity(\'kPa\')\n"
"App.Units.MegaPascal    = App.Units.Quantity(\'MPa\')\n"
"App.Units.GigaPascal    = App.Units.Quantity(\'GPa\')\n"
"\n"
"App.Units.MilliBar      = App.Units.Quantity(\'mbar\')\n"
"App.Units.Bar           = App.Units.Quantity(\'bar\')\n"
"\n"
"App.Units.PoundForce    = App.Units.Quantity(\'lbf\')\n"
"App.Units.Torr          = App.Units.Quantity(\'Torr\')\n"
"App.Units.mTorr         = App.Units.Quantity(\'mTorr\')\n"
"App.Units.yTorr         = App.Units.Quantity(\'uTorr\')\n"
"\n"
"App.Units.PSI           = App.Units.Quantity(\'psi\')\n"
"App.Units.KSI           = App.Units.Quantity(\'ksi\')\n"
"App.Units.MPSI          = App.Units.Quantity(\'Mpsi\')\n"
"\n"
"App.Units.Watt          = App.Units.Quantity(\'W\')\n"
"App.Units.NanoWatt      = App.Units.Quantity(\'nW\')\n"
"App.Units.MicroWatt     = App.Units.Quantity(\'uW\')\n"
"App.Units.MilliWatt     = App.Units.Quantity(\'mW\')\n"
"App.Units.KiloWatt      = App.Units.Quantity(\'kW\')\n"
"App.Units.VoltAmpere    = App.Units.Quantity(\'VA\')\n"
"\n"
"App.Units.Volt          = App.Units.Quantity(\'V\')\n"
"App.Units.MilliVolt     = App.Units.Quantity(\'mV\')\n"
"App.Units.KiloVolt      = App.Units.Quantity(\'kV\')\n"
"\n"
"App.Units.MegaSiemens   = App.Units.Quantity(\'MS\')\n"
"App.Units.KiloSiemens   = App.Units.Quantity(\'kS\')\n"
"App.Units.Siemens       = App.Units.Quantity(\'S\')\n"
"App.Units.MilliSiemens  = App.Units.Quantity(\'mS\')\n"
"App.Units.MicroSiemens  = App.Units.Quantity(\'uS\')\n"
"\n"
"App.Units.Ohm          = App.Units.Quantity(\'Ohm\')\n"
"App.Units.KiloOhm      = App.Units.Quantity(\'kOhm\')\n"
"App.Units.MegaOhm      = App.Units.Quantity(\'MOhm\')\n"
"\n"
"App.Units.Coulomb       = App.Units.Quantity(\'C\')\n"
"\n"
"App.Units.Tesla         = App.Units.Quantity(\'T\')\n"
"App.Units.Gauss         = App.Units.Quantity(\'G\')\n"
"\n"
"App.Units.Weber         = App.Units.Quantity(\'Wb\')\n"
"\n"
"# disable Oersted because people need to input e.g. a field strength of\n"
"# 1 ampere per meter -> 1 A/m and not get the recalculation to Oersted\n"
"# App.Units.Oersted       = App.Units.Quantity(\'Oe\')\n"
"\n"
"App.Units.PicoFarad     = App.Units.Quantity(\'pF\')\n"
"App.Units.NanoFarad     = App.Units.Quantity(\'nF\')\n"
"App.Units.MicroFarad    = App.Units.Quantity(\'uF\')\n"
"App.Units.MilliFarad    = App.Units.Quantity(\'mF\')\n"
"App.Units.Farad         = App.Units.Quantity(\'F\')\n"
"\n"
"App.Units.NanoHenry     = App.Units.Quantity(\'nH\')\n"
"App.Units.MicroHenry    = App.Units.Quantity(\'uH\')\n"
"App.Units.MilliHenry    = App.Units.Quantity(\'mH\')\n"
"App.Units.Henry         = App.Units.Quantity(\'H\')\n"
"\n"
"App.Units.Joule         = App.Units.Quantity(\'J\')\n"
"App.Units.MilliJoule    = App.Units.Quantity(\'mJ\')\n"
"App.Units.KiloJoule     = App.Units.Quantity(\'kJ\')\n"
"App.Units.NewtonMeter   = App.Units.Quantity(\'Nm\')\n"
"App.Units.VoltAmpereSecond   = App.Units.Quantity(\'VAs\')\n"
"App.Units.WattSecond    = App.Units.Quantity(\'Ws\')\n"
"App.Units.KiloWattHour  = App.Units.Quantity(\'kWh\')\n"
"App.Units.ElectronVolt  = App.Units.Quantity(\'eV\')\n"
"App.Units.KiloElectronVolt = App.Units.Quantity(\'keV\')\n"
"App.Units.MegaElectronVolt = App.Units.Quantity(\'MeV\')\n"
"App.Units.Calorie       = App.Units.Quantity(\'cal\')\n"
"App.Units.KiloCalorie   = App.Units.Quantity(\'kcal\')\n"
"\n"
"App.Units.MPH           = App.Units.Quantity(\'mi/h\')\n"
"App.Units.KMH           = App.Units.Quantity(\'km/h\')\n"
"\n"
"App.Units.Degree        = App.Units.Quantity(\'deg\')\n"
"App.Units.Radian        = App.Units.Quantity(\'rad\')\n"
"App.Units.Gon           = App.Units.Quantity(\'gon\')\n"
"App.Units.AngularMinute = App.Units.Quantity().AngularMinute\n"
"App.Units.AngularSecond = App.Units.Quantity().AngularSecond\n"
"\n"
"\n"
"# SI base units\n"
"# (length, weight, time, current, temperature, amount of substance, luminous intensity, angle)\n"
"App.Units.AmountOfSubstance           = App.Units.Unit(0,0,0,0,0,1)\n"
"App.Units.ElectricCurrent             = App.Units.Unit(0,0,0,1)\n"
"App.Units.Length                      = App.Units.Unit(1)\n"
"App.Units.LuminousIntensity           = App.Units.Unit(0,0,0,0,0,0,1)\n"
"App.Units.Mass                        = App.Units.Unit(0,1)\n"
"App.Units.Temperature                 = App.Units.Unit(0,0,0,0,1)\n"
"App.Units.TimeSpan                    = App.Units.Unit(0,0,1)\n"
"\n"
"# all other combined units\n"
"App.Units.Acceleration                = App.Units.Unit(1,0,-2)\n"
"App.Units.Angle                       = App.Units.Unit(0,0,0,0,0,0,0,1)\n"
"App.Units.AngleOfFriction             = App.Units.Unit(0,0,0,0,0,0,0,1)\n"
"App.Units.Area                        = App.Units.Unit(2)\n"
"App.Units.CompressiveStrength         = App.Units.Unit(-1,1,-2)\n"
"App.Units.CurrentDensity              = App.Units.Unit(-2,0,0,1)\n"
"App.Units.Density                     = App.Units.Unit(-3,1)\n"
"App.Units.DissipationRate             = App.Units.Unit(2,0,-3)\n"
"App.Units.DynamicViscosity            = App.Units.Unit(-1,1,-1)\n"
"App.Units.Frequency                   = App.Units.Unit(0,0,-1)\n"
"App.Units.MagneticFluxDensity         = App.Units.Unit(0,1,-2,-1)\n"
"App.Units.Magnetization               = App.Units.Unit(-1,0,0,1)\n"
"App.Units.ElectricalCapacitance       = App.Units.Unit(-2,-1,4,2)\n"
"App.Units.ElectricalConductance       = App.Units.Unit(-2,-1,3,2)\n"
"App.Units.ElectricalConductivity      = App.Units.Unit(-3,-1,3,2)\n"
"App.Units.ElectricalInductance        = App.Units.Unit(2,1,-2,-2)\n"
"App.Units.ElectricalResistance        = App.Units.Unit(2,1,-3,-2)\n"
"App.Units.ElectricCharge              = App.Units.Unit(0,0,1,1)\n"
"App.Units.ElectricPotential           = App.Units.Unit(2,1,-3,-1)\n"
"App.Units.Force                       = App.Units.Unit(1,1,-2)\n"
"App.Units.HeatFlux                    = App.Units.Unit(0,1,-3,0,0)\n"
"App.Units.InverseArea                 = App.Units.Unit(-2)\n"
"App.Units.InverseLength               = App.Units.Unit(-1)\n"
"App.Units.InverseVolume               = App.Units.Unit(-3)\n"
"App.Units.KinematicViscosity          = App.Units.Unit(2,0,-1)\n"
"App.Units.Pressure                    = App.Units.Unit(-1,1,-2)\n"
"App.Units.Power                       = App.Units.Unit(2,1,-3)\n"
"App.Units.ShearModulus                = App.Units.Unit(-1,1,-2)\n"
"App.Units.SpecificEnergy              = App.Units.Unit(2,0,-2)\n"
"App.Units.SpecificHeat                = App.Units.Unit(2,0,-2,0,-1)\n"
"App.Units.Stiffness                   = App.Units.Unit(0,1,-2)\n"
"App.Units.Stress                      = App.Units.Unit(-1,1,-2)\n"
"App.Units.ThermalConductivity         = App.Units.Unit(1,1,-3,0,-1)\n"
"App.Units.ThermalExpansionCoefficient = App.Units.Unit(0,0,0,0,-1)\n"
"App.Units.ThermalTransferCoefficient  = App.Units.Unit(0,1,-3,0,-1)\n"
"App.Units.UltimateTensileStrength     = App.Units.Unit(-1,1,-2)\n"
"App.Units.Velocity                    = App.Units.Unit(1,0,-1)\n"
"App.Units.VacuumPermittivity          = App.Units.Unit(-3,-1,4,2)\n"
"App.Units.Volume                      = App.Units.Unit(3)\n"
"App.Units.VolumeFlowRate              = App.Units.Unit(3,0,-1)\n"
"App.Units.VolumetricThermalExpansionCoefficient = App.Units.Unit(0,0,0,0,-1)\n"
"App.Units.Work                        = App.Units.Unit(2,1,-2)\n"
"App.Units.YieldStrength               = App.Units.Unit(-1,1,-2)\n"
"App.Units.YoungsModulus               = App.Units.Unit(-1,1,-2)\n"
"# fmt: on\n"
"\n"
"# The values must match with that of the\n"
"# C++ enum class UnitSystem\n"
"class Scheme(IntEnum):\n"
"    Internal = 0\n"
"    MKS = 1\n"
"    Imperial = 2\n"
"    ImperialDecimal = 3\n"
"    Centimeter = 4\n"
"    ImperialBuilding = 5\n"
"    MmMin = 6\n"
"    ImperialCivil = 7\n"
"    FEM = 8\n"
"    MeterDecimal = 9\n"
"\n"
"App.Units.Scheme = Scheme\n"
"\n"
"class NumberFormat(IntEnum):\n"
"    Default = 0\n"
"    Fixed = 1\n"
"    Scientific = 2\n"
"\n"
"App.Units.NumberFormat = NumberFormat\n"
"\n"
"class ScaleType(IntEnum):\n"
"    Other = -1\n"
"    NoScaling = 0\n"
"    NonUniformRight = 1\n"
"    NonUniformLeft = 2\n"
"    Uniform = 3\n"
"\n"
"App.ScaleType = ScaleType\n"
"\n"
"class PropertyType(IntEnum):\n"
"    Prop_None = 0\n"
"    Prop_ReadOnly = 1\n"
"    Prop_Transient = 2\n"
"    Prop_Hidden = 4\n"
"    Prop_Output = 8\n"
"    Prop_NoRecompute = 16\n"
"    Prop_NoPersist = 32\n"
"\n"
"App.PropertyType = PropertyType\n"
"\n"
"class ReturnType(IntEnum):\n"
"    PyObject = 0\n"
"    DocObject = 1\n"
"    DocAndPyObject = 2\n"
"    Placement = 3\n"
"    Matrix = 4\n"
"    LinkAndPlacement = 5\n"
"    LinkAndMatrix = 6\n"
"\n"
"App.ReturnType = ReturnType\n"
"\n"
"\n"
"# ┌────────────────────────────────────────────────┐\n"
"# │ Init Framework                                 │\n"
"# └────────────────────────────────────────────────┘\n"
"\n"
"class Transient:\n"
"    \"\"\"\n"
"    Mark the symbol for removal from global scope on cleanup.\n"
"    \"\"\"\n"
"\n"
"    names = [\"Path\"]\n"
"\n"
"    def __call__(self, target):\n"
"        Transient.names.append(target.__name__)\n"
"        return target\n"
"\n"
"    @classmethod\n"
"    def cleanup(cls) -> None:\n"
"        # Remove imports\n"
"        # os: kept for backwards compat\n"
"        keep = set((\"__builtins__\", \"FreeCAD\", \"App\", \"os\", \"sys\", \"traceback\", \"inspect\"))\n"
"        names = [name for name, ref in globals().items() if isinstance(ref, types.ModuleType)]\n"
"        for name in names:\n"
"            if name not in keep:\n"
"                del globals()[name]\n"
"\n"
"        # Remove transient symbols\n"
"        cls.names.extend((\"transient\", cls.__name__))\n"
"        for name in cls.names:\n"
"            del globals()[name]\n"
"\n"
"\n"
"transient = Transient()\n"
"\n"
"\n"
"@transient\n"
"def call_in_place(fn):\n"
"    \"\"\"Call the function in place immediately after its definition.\"\"\"\n"
"    fn()\n"
"    return fn\n"
"\n"
"@transient\n"
"class utils:\n"
"    HLine = \"-\" * 80\n"
"\n"
"    @staticmethod\n"
"    def str_to_paths(paths: str, delim: str = \";\") -> list[Path]:\n"
"        \"\"\"Convert a delimited string list of paths to a list of Path objects.\"\"\"\n"
"        items = (item.strip() for item in paths.split(delim))\n"
"        # Filtering out empty paths: This may break backwards compat or not.\n"
"        # If something breaks, just remove the filter to allow empty paths\n"
"        non_empty_paths = filter(bool, items)\n"
"        return list(map(Path, non_empty_paths))\n"
"\n"
"    @staticmethod\n"
"    def env_to_path(name: str) -> Path | None:\n"
"        if path := os.environ.get(name):\n"
"            return Path(path)\n"
"        return None\n"
"\n"
"    @staticmethod\n"
"    def setup_tty_tab_completion():\n"
"        \"\"\"\n"
"        Tries to setup readline-based tab-completion.\n"
"\n"
"        Call this function only if you are in a tty-based REPL environment.\n"
"        \"\"\"\n"
"        try:\n"
"            import readline\n"
"            import rlcompleter  # noqa: F401, import required\n"
"            readline.parse_and_bind(\"tab: complete\")\n"
"        except ImportError:\n"
"            # Note: As there is no readline on Windows,\n"
"            #       we just ignore import errors here.\n"
"            pass\n"
"\n"
"\n"
"@transient\n"
"class PathPriority(IntEnum):\n"
"    Ignore = 0\n"
"    FallbackLast = 1\n"
"    FallbackFirst = 2\n"
"    OverrideLast = 3\n"
"    OverrideFirst = 4\n"
"\n"
"@transient\n"
"@dataclasses.dataclass\n"
"class PathSet:\n"
"    \"\"\"\n"
"    Collection of paths with priority support.\n"
"\n"
"    Items can be inserted at specific priorities and composed in nested levels.\n"
"\n"
"    Structure:\n"
"    [\n"
"        override:(OverrideFirst, *_, OverrideLast),\n"
"        *source,\n"
"        fallback:(FallbackFirst, *_, FallbackLast),\n"
"    ]\n"
"    \"\"\"\n"
"\n"
"    source: list[\"Path | PathSet\"] = dataclasses.field(default_factory=list)\n"
"    override: collections.deque[\"Path | PathSet\"] = dataclasses.field(default_factory=collections.deque)\n"
"    fallback: collections.deque[\"Path | PathSet\"] = dataclasses.field(default_factory=collections.deque)\n"
"\n"
"    def add(self, item: \"Path | PathSet\", priority: PathPriority = PathPriority.OverrideLast) -> None:\n"
"        \"\"\"Add item into the corresponding priority slot.\"\"\"\n"
"        if isinstance(item, Path):\n"
"            item = item.resolve()\n"
"            if not item.exists():\n"
"                return\n"
"\n"
"        if priority == PathPriority.FallbackLast:\n"
"            self.fallback.append(item)\n"
"        elif priority == PathPriority.OverrideFirst:\n"
"            self.override.appendleft(item)\n"
"        elif priority == PathPriority.OverrideLast:\n"
"            self.override.append(item)\n"
"        elif priority == PathPriority.FallbackFirst:\n"
"            self.fallback.appendleft(item)\n"
"        elif priority == PathPriority.Ignore:\n"
"            pass\n"
"        else:\n"
"            msg = \"Invalid path priority\"\n"
"            raise ValueError(msg)\n"
"\n"
"    def iter(self) -> coll_abc.Iterable[Path]:\n"
"        \"\"\"\n"
"        Return iterable in priority order, higher first.\n"
"        \"\"\"\n"
"        for section in (self.override, self.source, self.fallback):\n"
"            for path in section:\n"
"                if isinstance(path, PathSet):\n"
"                    yield from path.iter()\n"
"                else:\n"
"                    yield path\n"
"\n"
"    def build(self) -> list[Path]:\n"
"        \"\"\"\n"
"        Build and remove duplicates, keep priority order.\n"
"        \"\"\"\n"
"        return list(dict.fromkeys(self.iter()))\n"
"\n"
"@transient\n"
"class SearchPaths:\n"
"    \"\"\"\n"
"    Manages search paths for binaries, libraries and modules.\n"
"\n"
"    The most generic search path is PATH in environment.\n"
"    DLL search path is windows specific.\n"
"    sys.path is for module imports.\n"
"    \"\"\"\n"
"\n"
"    env_path: PathSet\n"
"    sys_path: PathSet\n"
"    dll_path: PathSet\n"
"\n"
"    def __init__(self):\n"
"        self.env_path = PathSet([Path(p) for p in os.environ.get(\"PATH\", \"\").split(os.pathsep)])\n"
"        self.sys_path = PathSet(sys.path)\n"
"        self.dll_path = PathSet()\n"
"\n"
"    def add(\n"
"        self,\n"
"        item: Path | PathSet,\n"
"        *,\n"
"        env_path: PathPriority = PathPriority.OverrideLast,\n"
"        sys_path: PathPriority = PathPriority.OverrideFirst,\n"
"        dll_path: PathPriority = PathPriority.OverrideLast\n"
"    ) -> None:\n"
"        \"\"\"\n"
"        Add item to required namespaces with the specified priority.\n"
"\n"
"        Actual changes are buffered until commit().\n"
"        \"\"\"\n"
"        self.env_path.add(item, env_path)\n"
"        self.sys_path.add(item, sys_path)\n"
"        self.dll_path.add(item, dll_path)\n"
"\n"
"    def commit(self) -> None:\n"
"        \"\"\"Apply changes to underlying namespaces and priorities.\"\"\"\n"
"        os.environ[\"PATH\"] = os.pathsep.join(str(path) for path in self.env_path.build())\n"
"        sys.path = [str(path) for path in self.sys_path.build()]\n"
"\n"
"        if win32 := WindowsPlatform():\n"
"            win32.add_dll_search_paths(self.dll_path.build())\n"
"\n"
"        # Reset\n"
"        self.__init__()\n"
"\n"
"\n"
"@transient\n"
"class Config:\n"
"    AdditionalModulePaths = utils.str_to_paths(App.ConfigGet(\"AdditionalModulePaths\"))\n"
"    AdditionalMacroPaths = utils.str_to_paths(App.ConfigGet(\"AdditionalMacroPaths\"))\n"
"    RunMode: str = App.ConfigGet(\'RunMode\')\n"
"    DisabledAddons: set[str] = set(mod for mod in App.ConfigGet(\"DisabledAddons\").split(\";\") if mod)\n"
"\n"
"\n"
"@transient\n"
"class WindowsPlatform:\n"
"    \"\"\"\n"
"    Windows specific hooks.\n"
"    \"\"\"\n"
"\n"
"    initialized = False\n"
"    enabled = platform.system() == \'Windows\' and hasattr(os, \"add_dll_directory\")\n"
"\n"
"    def __init__(self) -> None:\n"
"        if not WindowsPlatform.enabled or WindowsPlatform.initialized:\n"
"            return\n"
"\n"
"        if lib_pack := utils.env_to_path(\"FREECAD_LIBPACK_BIN\"):\n"
"            os.add_dll_directory(str(lib_pack.resolve()))\n"
"        if win_dir := utils.env_to_path(\"WINDIR\"):\n"
"            system32 = win_dir / \"system32\"\n"
"            os.add_dll_directory(str(system32.resolve()))\n"
"\n"
"        WindowsPlatform.initialized = True\n"
"\n"
"    def __bool__(self) -> bool:\n"
"        return self.enabled\n"
"\n"
"    def add_dll_search_paths(self, paths: list[Path]) -> None:\n"
"        for path in paths:\n"
"            os.add_dll_directory(str(path.resolve()))\n"
"\n"
"\n"
"@transient\n"
"class DarwinPlatform:\n"
"    \"\"\"\n"
"    MacOSX specific hooks.\n"
"    \"\"\"\n"
"\n"
"    enabled = platform.system() == \"Darwin\" and len(platform.mac_ver()[0]) > 0\n"
"\n"
"    def __bool__(self) -> bool:\n"
"        return self.enabled\n"
"\n"
"    def post(self) -> None:\n"
"        # add special path for MacOSX (bug #0000307): Where is this bug documented?\n"
"        sys.path.append(os.path.expanduser(\"~/Library/Application Support/FreeCAD/Mod\"))\n"
"\n"
"\n"
"class ModState(IntEnum):\n"
"    Unsupported = -3\n"
"    Failed = -2\n"
"    Disabled = -1\n"
"    Discovered = 0\n"
"    Resolved = 1\n"
"    Loaded = 2\n"
"\n"
"\n"
"@transient\n"
"class Mod:\n"
"    \"\"\"\n"
"    Base Mod.\n"
"\n"
"    There are two types of Mods: Directory based (DirMod) or Module based (ExtMod).\n"
"    \"\"\"\n"
"\n"
"    ALL_ADDONS_DISABLED = \"ALL_ADDONS_DISABLED\"\n"
"    ADDON_DISABLED = \"ADDON_DISABLED\"\n"
"    PACKAGE_XML = \"package.xml\"\n"
"\n"
"    state: ModState\n"
"\n"
"    @property\n"
"    def kind(self) -> str:\n"
"        \"\"\"Return the Mod type: \'Dir\' or \'Ext\'\"\"\"\n"
"        return \"Ext\"\n"
"\n"
"    @property\n"
"    def init_mode(self) -> str:\n"
"        \"\"\"Return the Mod init mode: \'exec\' or \'import\' or \'\'\"\"\"\n"
"        return \"import\"\n"
"\n"
"    @property\n"
"    def metadata(self) -> App.Metadata | None:\n"
"        \"\"\"Return Metadata from package.xml if any.\"\"\"\n"
"\n"
"    def check_disabled(self) -> bool:\n"
"        \"\"\"\n"
"        Mods can be disabled by several methods:\n"
"        - command line argument: --disable-addon <name>\n"
"        - stop file: ALL_ADDONS_DISABLED\n"
"        - stop file: ADDON_DISABLED\n"
"        \"\"\"\n"
"\n"
"    def process_metadata(self, search_paths: SearchPaths) -> None:\n"
"        \"\"\"\n"
"        Process package.xml if present to check version compatibility and to scan internal workbenches.\n"
"        \"\"\"\n"
"\n"
"    def run_init(self) -> None:\n"
"        \"\"\"\n"
"        Run all required initialization scripts/modules: Init.py, init, __init__.py\n"
"        \"\"\"\n"
"\n"
"    def supports_freecad_version(self) -> bool:\n"
"        \"\"\"\n"
"        Check if the Mod supports the current FreeCAD version.\n"
"        \"\"\"\n"
"        if meta := self.metadata:\n"
"            return meta.supportsCurrentFreeCAD()\n"
"        return True\n"
"\n"
"    def load(self, search_paths: SearchPaths) -> None:\n"
"        \"\"\"\n"
"        Load the Mod.\n"
"        \"\"\"\n"
"        try:\n"
"            self.process_metadata(search_paths)\n"
"        except Exception as ex:\n"
"            self.state = ModState.Failed\n"
"            Err(str(ex))\n"
"        else:\n"
"            if self.state == ModState.Resolved:\n"
"                self.run_init()\n"
"                if self.state == ModState.Resolved:\n"
"                    self.state = ModState.Loaded\n"
"\n"
"\n"
"@transient\n"
"class ExtMod(Mod):\n"
"    \"\"\"\n"
"    Module based Mod (aka extension module).\n"
"\n"
"    This kind of Mods are loaded using python module system, no direct filesystem or\n"
"    compile/execute hacks are used.\n"
"\n"
"    extension modules must be defined in namespace freecad.*, i.e. freecad.MyAddon.\n"
"    \"\"\"\n"
"\n"
"    name: str  # full module name, i.e.: freecad.MyAddon\n"
"\n"
"    def __init__(self, name: str):\n"
"        self.state = ModState.Resolved\n"
"        self.name = name\n"
"\n"
"    @functools.cached_property\n"
"    def metadata(self) -> App.Metadata | None:\n"
"        with resources.as_file(resources.files(self.name)) as base:\n"
"            metadata = base / self.PACKAGE_XML\n"
"            if metadata.exists():\n"
"                return App.Metadata(str(metadata))\n"
"            metadata = base.parent.parent / self.PACKAGE_XML\n"
"            if metadata.exists():\n"
"                return App.Metadata(str(metadata))\n"
"        return None\n"
"\n"
"    def check_disabled(self) -> bool:\n"
"        with resources.as_file(resources.files(self.name)) as base:\n"
"            return (base / self.ADDON_DISABLED).exists() or (base.parent.parent / self.ADDON_DISABLED).exists()\n"
"\n"
"    def process_metadata(self, _search_paths: SearchPaths) -> None:\n"
"        meta = self.metadata\n"
"        if not meta:\n"
"            return\n"
"\n"
"        if not self.supports_freecad_version():\n"
"            self.state = ModState.Unsupported\n"
"            Msg(f\"NOTICE: {self.name} does not support this version of FreeCAD, so is being skipped\")\n"
"\n"
"    def _init_error(self, ex: Exception, error_msg: str) -> None:\n"
"        Err(f\'During initialization the error \"{ex!s}\" occurred in {self.name}\')\n"
"        Err(utils.HLine)\n"
"        Err(error_msg)\n"
"        Err(utils.HLine)\n"
"        Log(f\'Init:      Initializing {self.name}... failed\')\n"
"        Err(utils.HLine)\n"
"        Log(error_msg)\n"
"        Err(utils.HLine)\n"
"\n"
"    def run_init(self) -> None:\n"
"        try:\n"
"            module = importlib.import_module(self.name) # Implicit run of __init__.py\n"
"        except Exception as ex:\n"
"            self._init_error(ex, traceback.format_exc())\n"
"            self.state = ModState.Failed\n"
"        else:\n"
"            self.run_secondary_init(module)\n"
"\n"
"    def run_secondary_init(self, module: types.ModuleType) -> None:\n"
"        try:\n"
"            importlib.import_module(f\"{module.__name__}.init\")\n"
"        except ModuleNotFoundError:\n"
"            pass  # Ok, this module is optional\n"
"        except Exception as ex:\n"
"            self._init_error(ex, traceback.format_exc())\n"
"            self.state = ModState.Failed\n"
"\n"
"\n"
"@transient\n"
"class DirMod(Mod):\n"
"    \"\"\"\n"
"    Directory based Mod. (aka Standard/Legacy).\n"
"\n"
"    This kind of Mods are scanned from several directories in the system\n"
"    following certain priority. The name part of the path is used\n"
"    as the module name.\n"
"\n"
"    Dir based modules can be overridden if several copies exists in different directories,\n"
"    resolution is based on directory priority.\n"
"    \"\"\"\n"
"\n"
"    INIT_PY = \"Init.py\"\n"
"\n"
"    _path: collections.deque[Path]\n"
"\n"
"    def __init__(self, path: Path) -> None:\n"
"        self.state = ModState.Discovered\n"
"        self._path = collections.deque()\n"
"        self._path.append(path)\n"
"\n"
"    @property\n"
"    def kind(self) -> str:\n"
"        return \"Dir\"\n"
"\n"
"    @property\n"
"    def init_mode(self) -> str:\n"
"        return \"exec\" if (self.path / self.INIT_PY).exists() else \'\'\n"
"\n"
"    @property\n"
"    def name(self) -> str:\n"
"        return self.path.name\n"
"\n"
"    @functools.cached_property\n"
"    def metadata(self) -> App.Metadata | None:\n"
"        metadata = self.path / self.PACKAGE_XML\n"
"        if metadata.exists():\n"
"            return App.Metadata(str(metadata))\n"
"        return None\n"
"\n"
"    def process_metadata(self, search_paths: SearchPaths):\n"
"        meta = self.metadata\n"
"        if not meta:\n"
"            return\n"
"\n"
"        if not self.supports_freecad_version():\n"
"            self.state = ModState.Unsupported\n"
"            Msg(f\"NOTICE: {meta.Name} does not support this version of FreeCAD, so is being skipped\")\n"
"            return\n"
"\n"
"        content = meta.Content\n"
"        if \"workbench\" in content:\n"
"            workbenches = content[\"workbench\"]\n"
"            for workbench in workbenches:\n"
"                if not workbench.supportsCurrentFreeCAD():\n"
"                    Msg(f\"NOTICE: {meta.Name} content item {workbench.Name} does not support this version of FreeCAD, so is being skipped\")\n"
"                    continue\n"
"\n"
"                subdirectory = workbench.Name if not workbench.Subdirectory else workbench.Subdirectory\n"
"                subdirectory = re.split(r\"[/\\\\]+\", subdirectory)\n"
"                subdirectory = self.path / Path(*subdirectory)\n"
"\n"
"                search_paths.add(\n"
"                    subdirectory,\n"
"                    env_path=PathPriority.OverrideLast,\n"
"                    sys_path=PathPriority.OverrideFirst,\n"
"                    dll_path=PathPriority.FallbackLast,\n"
"                )\n"
"\n"
"    def override_with(self, path: Path) -> None:\n"
"        \"\"\"\n"
"        Override current path with the one provided.\n"
"        \"\"\"\n"
"        self._path.appendleft(path)\n"
"\n"
"    @property\n"
"    def path(self) -> Path:\n"
"        \"\"\"Current (highest priority) path.\"\"\"\n"
"        return self._path[0]\n"
"\n"
"    @property\n"
"    def alternative_paths(self) -> list[Path]:\n"
"        \"\"\"Alternative paths in priority order\"\"\"\n"
"        return list(self._path)[1:]\n"
"\n"
"    def check_disabled(self) -> bool:\n"
"        name = self.path.name\n"
"\n"
"        if name in Config.DisabledAddons:\n"
"            Msg(f\'NOTICE: Addon \"{name}\" disabled by presence of \"--disable-addon {name}\" argument\')\n"
"            return True\n"
"\n"
"        for flag in (self.ALL_ADDONS_DISABLED, self.ADDON_DISABLED):\n"
"            if (self.path / flag).exists():\n"
"                Msg(f\'NOTICE: Addon \"{self.path!s}\" disabled by presence of {flag} stopfile\')\n"
"                return True\n"
"\n"
"        return False\n"
"\n"
"    def resolve(self, search_paths: SearchPaths) -> None:\n"
"        \"\"\"\n"
"        Add the current path to search paths to make it loadable.\n"
"        \"\"\"\n"
"        if self.check_disabled():\n"
"            self.state = ModState.Disabled\n"
"            return\n"
"\n"
"        search_paths.add(\n"
"            self.path,\n"
"            env_path=PathPriority.OverrideLast,\n"
"            sys_path=PathPriority.OverrideFirst,\n"
"        )\n"
"\n"
"        self.state = ModState.Resolved\n"
"\n"
"    def run_init(self) -> None:\n"
"        init_py = self.path / self.INIT_PY\n"
"        if not init_py.exists():\n"
"            self.state = ModState.Loaded\n"
"            Log(f\"Init:      Initializing {self.path!s} ({self.INIT_PY} not found)... ignore\")\n"
"            return\n"
"\n"
"        try:\n"
"            source = init_py.read_text(encoding=\"utf-8\")\n"
"            code = compile(source, init_py, \'exec\')\n"
"            exec(code)\n"
"        except Exception as ex:\n"
"            Log(f\"Init:      Initializing {self.path!s}... failed\")\n"
"            Log(utils.HLine)\n"
"            Log(f\"{traceback.format_exc()}\")\n"
"            Log(utils.HLine)\n"
"            Err(f\"During initialization the error \\\"{ex!s}\\\" occurred in {init_py!s}\")\n"
"            Err(\"Please look into the log file for further information\")\n"
"            self.state = ModState.Failed\n"
"        else:\n"
"            self.state = ModState.Loaded\n"
"            Log(f\"Init:      Initializing {self.path!s}... done\")\n"
"\n"
"\n"
"@transient\n"
"class ExtModScanner:\n"
"    \"\"\"\n"
"    Scan extension Mods from the python import path.\n"
"    \"\"\"\n"
"\n"
"    mods: list[ExtMod]\n"
"\n"
"    def __init__(self):\n"
"        self.mods = []\n"
"\n"
"    def scan(self):\n"
"        import freecad\n"
"        modules = (m[1] for m in pkgutil.iter_modules(freecad.__path__, \"freecad.\") if m[2])\n"
"        for module_name in modules:\n"
"            mod = ExtMod(module_name)\n"
"            self.mods.append(mod)\n"
"            if module_name in Config.DisabledAddons:\n"
"                mod.state = ModState.Disabled\n"
"                Msg(f\'NOTICE: Addon \"{module_name}\" disabled by presence of \"--disable-addon {module_name}\" argument\')\n"
"                continue\n"
"            Log(f\'Init:      Initializing {module_name}\')\n"
"\n"
"    def iter(self) -> coll_abc.Iterable[ExtMod]:\n"
"        return self.mods\n"
"\n"
"\n"
"@transient\n"
"class DirModScanner:\n"
"    \"\"\"\n"
"    Sacan in the filesystem for Dir based Mods in the valid locations.\n"
"    \"\"\"\n"
"\n"
"    EXCLUDE: set[str] = set([\"\", \"CVS\", \"__init__.py\"]) # Why?\n"
"    mods: dict[str, DirMod]\n"
"    visited: set[str]\n"
"\n"
"    def __init__(self) -> None:\n"
"        self.mods = {}\n"
"        self.visited = set()\n"
"\n"
"    def iter(self) -> coll_abc.Iterable[DirMod]:\n"
"        \"\"\"All discovered Mods.\"\"\"\n"
"        return self.mods.values()\n"
"\n"
"    def dirs(self) -> list[Path]:\n"
"        \"\"\"Paths of all discovered Mods.\"\"\"\n"
"        return [mod.path for mod in self.mods.values()]\n"
"\n"
"    def scan_and_override(self, base: Path, *, flat: bool = False, warning: str | None = None) -> None:\n"
"        \"\"\"\n"
"        Scan in base with higher priority.\n"
"        \"\"\"\n"
"        if (key := str(base.resolve())) in self.visited:\n"
"            return\n"
"\n"
"        self.visited.add(key)\n"
"\n"
"        if not base.exists():\n"
"            if warning:\n"
"                Wrn(warning)\n"
"            return\n"
"\n"
"        if warning:\n"
"            Wrn(warning)\n"
"\n"
"        if flat:\n"
"            self.mods[str(base)] = DirMod(base)\n"
"            return\n"
"\n"
"        for mod_dir in filter(Path.is_dir, base.iterdir()):\n"
"            name = mod_dir.name.lower()\n"
"            if name in DirModScanner.EXCLUDE:\n"
"                continue\n"
"\n"
"            if mod := self.mods.get(name):\n"
"                mod.override_with(mod_dir)\n"
"                continue\n"
"\n"
"            self.mods[name] = DirMod(mod_dir)\n"
"\n"
"\n"
"# ┌────────────────────────────────────────────────┐\n"
"# │ Init Pipeline Definition                       │\n"
"# └────────────────────────────────────────────────┘\n"
"\n"
"@transient\n"
"class InitPipeline:\n"
"    \"\"\"\n"
"    Init sequence, setup search paths, scan and load Mods and run platform specific hooks.\n"
"    \"\"\"\n"
"\n"
"    std_home = Path(App.getHomePath()).resolve()\n"
"    user_home = Path(App.getUserAppDataDir()).resolve()\n"
"    try:\n"
"        std_lib = Path(App.getLibraryDir()).resolve()\n"
"    except OSError:\n"
"        # The library path is not strictly required, so if the OS itself raises an error when trying\n"
"        # to resolve it, just fall back to something reasonable. See #26864.\n"
"        std_lib = std_home / \"lib\"\n"
"        Log(f\"Resolving library directory \'{App.getLibraryDir()}\' failed, using fallback \'{std_lib}\'\")\n"
"    dir_mod_scanner = DirModScanner()\n"
"    ext_mod_scanner = ExtModScanner()\n"
"    search_paths = SearchPaths()\n"
"\n"
"    def added_python_packages(self) -> PathSet:\n"
"        \"\"\"\n"
"        Additional python packages installed by AddonManager/pip.\n"
"        \"\"\"\n"
"        major, minor, _ = platform.python_version_tuple()\n"
"        packages = self.user_home / \"AdditionalPythonPackages\"\n"
"        vendor_path = packages / f\"py{major}{minor}\"\n"
"        paths = PathSet()\n"
"        paths.add(vendor_path)\n"
"        paths.add(packages)\n"
"        return paths\n"
"\n"
"    def scan(self) -> None:\n"
"        \"\"\"\n"
"        Scan step, search for standard directories, libraries and Mods.\n"
"        \"\"\"\n"
"        std_home = self.std_home\n"
"        user_home = self.user_home\n"
"        std_lib = self.std_lib\n"
"        std_mod = std_home / \"Mod\"\n"
"        std_ext = std_home / \"Ext\"\n"
"        std_bin = std_home / \"bin\"\n"
"        user_macro = Path(App.getUserMacroDir(True)).resolve()\n"
"        user_mod = user_home / \"Mod\"\n"
"        search_paths = self.search_paths\n"
"\n"
"        legacy_user_mod = Path.home() / \".FreeCAD\" / \"Mod\"\n"
"        if legacy_user_mod.exists():\n"
"            Wrn (f\"User path has changed to {user_home!s}. Please move user modules and macros\")\n"
"\n"
"        # Libraries\n"
"        libraries = PathSet()\n"
"        libraries.add(std_home / \"lib\")\n"
"        libraries.add(std_home / \"lib64\")\n"
"        libraries.add(std_home / \"lib-py3\")\n"
"        libraries.add(std_lib)\n"
"\n"
"        search_paths.add(\n"
"            libraries,\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.OverrideLast,\n"
"        )\n"
"\n"
"        # Tools\n"
"        search_paths.add(\n"
"            std_home / \"Tools\",\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.FallbackLast,\n"
"        )\n"
"\n"
"        # Binaries\n"
"        search_paths.add(\n"
"            std_bin,\n"
"            env_path=PathPriority.OverrideFirst,\n"
"            sys_path=PathPriority.Ignore,\n"
"            dll_path=PathPriority.FallbackLast,\n"
"        )\n"
"\n"
"        # Scan for Directory based Mods\n"
"        # Order is important because of overrides\n"
"        Log(\"Init:   Searching for modules...\")\n"
"        mods = self.dir_mod_scanner\n"
"        mods.scan_and_override(std_mod)\n"
"        mods.scan_and_override(user_mod)\n"
"        mods.scan_and_override(user_macro / \"Mod\")\n"
"        additional_mods = Config.AdditionalModulePaths + Config.AdditionalMacroPaths\n"
"        for add in additional_mods:\n"
"            mods.scan_and_override(add, flat=True)\n"
"\n"
"        # to have all the module-paths available in FreeCADGuiInit.py:\n"
"        App.__ModDirs__ = [str(d) for d in mods.dirs()]\n"
"\n"
"        # this allows importing with:\n"
"        # from FreeCAD.Module import package\n"
"        import_path = PathSet([libraries])\n"
"        import_path.add(std_mod, PathPriority.OverrideFirst)\n"
"        import_path.add(user_mod, PathPriority.FallbackLast)\n"
"        App.__path__ = [str(path) for path in import_path.build()]\n"
"\n"
"        # also add these directories to the sys.path to\n"
"        # not change the old behavior. once we have moved to\n"
"        # proper python modules this can eventually be removed.\n"
"        search_paths.add(\n"
"            std_mod,\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.OverrideFirst,\n"
"        )\n"
"        search_paths.add(\n"
"            std_ext,\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.OverrideLast,\n"
"        )\n"
"\n"
"        # Additional installed packages (AddonManager/pip)\n"
"        search_paths.add(\n"
"            self.added_python_packages(),\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.FallbackLast,\n"
"        )\n"
"\n"
"        # Resolve Dir Mods\n"
"        for mod in mods.iter():\n"
"            mod.resolve(search_paths)\n"
"\n"
"    def load_mods(self) -> None:\n"
"        \"\"\"\n"
"        Load Mods step, load both Dir based and Module based Mods.\n"
"        \"\"\"\n"
"        module_cache = []\n"
"\n"
"        # Update search paths to make Mods visible to import system.\n"
"        search_paths = self.search_paths\n"
"        search_paths.commit()\n"
"\n"
"        # Dir Mods first\n"
"        for mod in self.dir_mod_scanner.iter():\n"
"            if mod.state == ModState.Resolved:\n"
"                mod.load(search_paths)\n"
"                module_cache.append(mod)\n"
"\n"
"        # Update search paths: may have changed by dir loads\n"
"        search_paths.commit()\n"
"\n"
"        # Finally, Module based Mod are loaded from python path\n"
"        self.ext_mod_scanner.scan()\n"
"        for mod in self.ext_mod_scanner.iter():\n"
"            if mod.state == ModState.Resolved:\n"
"                mod.load(search_paths)\n"
"                module_cache.append(mod)\n"
"\n"
"        # Save to use in FreeCADGuiInit.py\n"
"        App.__ModCache__ = module_cache\n"
"\n"
"    def register_macro_sources(self) -> None:\n"
"        \"\"\"\n"
"        Add Macro sources to search paths.\n"
"        \"\"\"\n"
"        std_macro = self.std_home / \"Macro\"\n"
"        user_macro_default = Path(App.getUserMacroDir(False)).resolve()\n"
"        user_macro = Path(App.getUserMacroDir(True)).resolve()\n"
"\n"
"        # add MacroDir to path (RFE #0000504)\n"
"        self.search_paths.add(\n"
"            user_macro_default,\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.FallbackLast,\n"
"        )\n"
"        self.search_paths.add(\n"
"            user_macro,\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.FallbackLast,\n"
"        )\n"
"        self.search_paths.add(\n"
"            std_macro,\n"
"            env_path=PathPriority.Ignore,\n"
"            sys_path=PathPriority.FallbackLast,\n"
"        )\n"
"        self.search_paths.commit()\n"
"\n"
"    def post(self) -> None:\n"
"        \"\"\"\n"
"        Run final steps.\n"
"        \"\"\"\n"
"        if macosx := DarwinPlatform():\n"
"            macosx.post()\n"
"\n"
"    def setup_tty(self) -> None:\n"
"        # Note: just checking whether stdin is a TTY is not enough, as the GUI is set up only after this\n"
"        # script has run. And checking only the RunMode is not enough, as we are maybe not interactive.\n"
"        if Config.RunMode == \'Cmd\' and hasattr(sys.stdin, \'isatty\') and sys.stdin.isatty():\n"
"            utils.setup_tty_tab_completion()\n"
"\n"
"    def report(self) -> None:\n"
"        std_mod = self.std_home / \"Mod\"\n"
"        Log(f\"Using {std_mod!s} as module path!\")\n"
"\n"
"        Log(\"System path after init:\")\n"
"        for path in os.environ[\"PATH\"].split(os.pathsep):\n"
"            Log(f\"   {path}\")\n"
"\n"
"        Log(\"FreeCADInit Mod summary:\")\n"
"        output = []\n"
"        output.append(f\"+-{\'--\':-<24}-+-{\'----\':-<10}-+-{\'---\':-<6}-+-{\'-----\':-<48}-\")\n"
"        output.append(f\"| {\'Mod\':<24} | {\'State\':<10} | {\'Mode\':<6} | {\'Source\':<48} \")\n"
"        output.append(output[0])\n"
"\n"
"        for mod in self.dir_mod_scanner.iter():\n"
"            output.append(f\"| {mod.name:<24.24} | {mod.state.name:<10.10} | {mod.init_mode:<6.6} | {mod.path!s}\")\n"
"            for alt in mod.alternative_paths:\n"
"                output.append(f\"| {\' \':<24.24} | {\' \':<10.10} | {\' \':<6.6} | {alt!s}\")\n"
"\n"
"        for mod in self.ext_mod_scanner.iter():\n"
"            output.append(f\"| {mod.name:<24.24} | {mod.state.name:<10.10} | {mod.init_mode:<6.6} | {mod.name}\")\n"
"\n"
"        for line in output:\n"
"            Log(line)\n"
"        Log(output[0])\n"
"\n"
"    def run(self) -> None:\n"
"        \"\"\"\n"
"        Pipeline entry point.\n"
"        \"\"\"\n"
"        self.scan()\n"
"        self.load_mods()\n"
"        self.register_macro_sources()\n"
"        self.post()\n"
"        self.report()\n"
"        self.setup_tty()\n"
"\n"
"\n"
"# ┌────────────────────────────────────────────────┐\n"
"# │ Init Applications                              │\n"
"# └────────────────────────────────────────────────┘\n"
"\n"
"@transient\n"
"@call_in_place\n"
"def init_applications() -> None:\n"
"    try:\n"
"        InitPipeline().run()\n"
"        Log(\'Init: App::FreeCADInit.py done\')\n"
"    except Exception as ex:\n"
"        Err(f\'Error in init_applications {ex!s}\')\n"
"        Err(utils.HLine)\n"
"        Err(traceback.format_exc())\n"
"        Err(utils.HLine)\n"
"\n"
"\n"
"# ┌────────────────────────────────────────────────┐\n"
"# │ Cleanup for next scripts                       │\n"
"# └────────────────────────────────────────────────┘\n"
"\n"
"# Reset logger to no extra newline for subsequent scripts (Backwards compat)\n"
"__logger.sep = \"\"\n"
"\n"
"# Clean global namespace\n"
"transient.cleanup()\n"
;


